Revert "defconfig: enable unwind"
/arch/arm/kernel/return_address.c:65:7: error: redefinition of 'return_address'
 void *return_address(unsigned int level)
       ^
In file included from /include/linux/ftrace.h:20:0,
                 from /arch/arm/kernel/return_address.c:12:
/arch/arm/include/asm/ftrace.h:48:21: note: previous definition of 'return_address' was here
 extern inline void *return_address(unsigned int level)

This reverts commit 529f5926685c85b0a6bdd307c989332f13a1d811.